var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/auth/callback/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ah~1_4._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_03dpqtp.js")
R.c("server/chunks/ssr/[root-of-the-server]__0noj4~-._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ja5ekc._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_@opentelemetry_api_index_0zv0b3p.js")
R.c("server/chunks/ssr/_0jp.40y._.js")
R.c("server/chunks/ssr/node_modules_@supabase_supabase-js_dist_index_mjs_04qodwz._.js")
R.c("server/chunks/ssr/_08cx7ty._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0ee1czk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/frontend__next-internal_server_app_auth_callback_page_actions_07vyypn.js")
R.m(57365)
module.exports=R.m(57365).exports
