// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin" | "/admin/categories" | "/admin/classifieds" | "/admin/events" | "/admin/faq" | "/admin/login" | "/admin/marketing" | "/admin/pending" | "/admin/pending/[id]" | "/admin/posts" | "/admin/posts/[id]/edit" | "/admin/posts/new" | "/admin/settings" | "/admin/users" | "/auth/callback" | "/classifieds" | "/classifieds/[id]" | "/contact" | "/faq" | "/install-app" | "/login" | "/posts/[id]" | "/privacy" | "/profile" | "/signup" | "/submit" | "/tos"
type AppRouteHandlerRoutes = "/api/admin/categories" | "/api/admin/classifieds" | "/api/admin/logout" | "/api/admin/marketing" | "/api/admin/settings" | "/api/admin/stats" | "/api/admin/subcategories" | "/api/admin/submissions/[id]" | "/api/admin/users" | "/api/auth/logout" | "/api/auth/me" | "/api/comments" | "/api/cron/expiry-notifications" | "/api/send-whatsapp" | "/api/submit" | "/api/track" | "/api/user/delete-post/[id]" | "/api/user/delete-submission/[id]" | "/api/user/published-posts" | "/api/user/submissions" | "/api/user/update-email" | "/api/user/update-nickname" | "/api/wa-auth/logout" | "/api/wa-auth/request-otp" | "/api/wa-auth/verify-otp"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin": {}
  "/admin/categories": {}
  "/admin/classifieds": {}
  "/admin/events": {}
  "/admin/faq": {}
  "/admin/login": {}
  "/admin/marketing": {}
  "/admin/pending": {}
  "/admin/pending/[id]": { "id": string; }
  "/admin/posts": {}
  "/admin/posts/[id]/edit": { "id": string; }
  "/admin/posts/new": {}
  "/admin/settings": {}
  "/admin/users": {}
  "/api/admin/categories": {}
  "/api/admin/classifieds": {}
  "/api/admin/logout": {}
  "/api/admin/marketing": {}
  "/api/admin/settings": {}
  "/api/admin/stats": {}
  "/api/admin/subcategories": {}
  "/api/admin/submissions/[id]": { "id": string; }
  "/api/admin/users": {}
  "/api/auth/logout": {}
  "/api/auth/me": {}
  "/api/comments": {}
  "/api/cron/expiry-notifications": {}
  "/api/send-whatsapp": {}
  "/api/submit": {}
  "/api/track": {}
  "/api/user/delete-post/[id]": { "id": string; }
  "/api/user/delete-submission/[id]": { "id": string; }
  "/api/user/published-posts": {}
  "/api/user/submissions": {}
  "/api/user/update-email": {}
  "/api/user/update-nickname": {}
  "/api/wa-auth/logout": {}
  "/api/wa-auth/request-otp": {}
  "/api/wa-auth/verify-otp": {}
  "/auth/callback": {}
  "/classifieds": {}
  "/classifieds/[id]": { "id": string; }
  "/contact": {}
  "/faq": {}
  "/install-app": {}
  "/login": {}
  "/posts/[id]": { "id": string; }
  "/privacy": {}
  "/profile": {}
  "/signup": {}
  "/submit": {}
  "/tos": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
