const { createClient } = require('@supabase/supabase-js');
const dotenv = require('dotenv');
const path = require('path');

dotenv.config({ path: path.resolve(__dirname, '../.env') });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.error('Missing Supabase credentials in .env');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

async function setupPolls() {
  console.log('Setting up Polls tables...');

  // 1. Create polls table
  const { error: pollsError } = await supabase.rpc('run_sql', {
    sql: `
      CREATE TABLE IF NOT EXISTS polls (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title TEXT NOT NULL,
        description TEXT,
        image_url TEXT,
        share_message TEXT,
        is_active BOOLEAN DEFAULT false,
        created_at TIMESTAMPTZ DEFAULT now()
      );

      CREATE TABLE IF NOT EXISTS poll_candidates (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        poll_id BIGINT REFERENCES polls(id) ON DELETE CASCADE,
        name TEXT NOT NULL,
        photo_url TEXT,
        seed_votes INTEGER DEFAULT 0,
        created_at TIMESTAMPTZ DEFAULT now()
      );

      CREATE TABLE IF NOT EXISTS poll_votes (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        poll_id BIGINT REFERENCES polls(id) ON DELETE CASCADE,
        user_id UUID REFERENCES wa_users(id) ON DELETE CASCADE,
        candidate_id BIGINT REFERENCES poll_candidates(id) ON DELETE CASCADE,
        created_at TIMESTAMPTZ DEFAULT now(),
        UNIQUE(poll_id, user_id)
      );

      -- Enable RLS (simplified for now, admin handles most)
      ALTER TABLE polls ENABLE ROW LEVEL SECURITY;
      ALTER TABLE poll_candidates ENABLE ROW LEVEL SECURITY;
      ALTER TABLE poll_votes ENABLE ROW LEVEL SECURITY;

      -- Policies
      CREATE POLICY "Public can view active polls" ON polls FOR SELECT USING (is_active = true);
      CREATE POLICY "Public can view candidates" ON poll_candidates FOR SELECT USING (true);
      CREATE POLICY "Authenticated users can vote" ON poll_votes FOR INSERT WITH CHECK (auth.uid() = user_id);
      CREATE POLICY "Users can see their own votes" ON poll_votes FOR SELECT USING (auth.uid() = user_id);
    `
  });

  if (pollsError) {
    console.error('Error creating tables:', pollsError);
    // Fallback: If RPC run_sql is not available, we might need another way or tell user.
    if (pollsError.message.includes('function run_sql(text) does not exist')) {
        console.log('RPC run_sql not found. Please run the SQL manually in Supabase SQL Editor:');
        console.log(`
        CREATE TABLE IF NOT EXISTS polls (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          title TEXT NOT NULL,
          description TEXT,
          image_url TEXT,
          share_message TEXT,
          is_active BOOLEAN DEFAULT false,
          created_at TIMESTAMPTZ DEFAULT now()
        );

        CREATE TABLE IF NOT EXISTS poll_candidates (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          poll_id BIGINT REFERENCES polls(id) ON DELETE CASCADE,
          name TEXT NOT NULL,
          photo_url TEXT,
          seed_votes INTEGER DEFAULT 0,
          created_at TIMESTAMPTZ DEFAULT now()
        );

        CREATE TABLE IF NOT EXISTS poll_votes (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          poll_id BIGINT REFERENCES polls(id) ON DELETE CASCADE,
          user_id UUID REFERENCES wa_users(id) ON DELETE CASCADE,
          candidate_id BIGINT REFERENCES poll_candidates(id) ON DELETE CASCADE,
          created_at TIMESTAMPTZ DEFAULT now(),
          UNIQUE(poll_id, user_id)
        );
        `);
    }
  } else {
    console.log('Tables created successfully!');
  }
}

setupPolls();
